GET http://localhost:4004/CatalogService/
###Read services' metadata
GET http://localhost:4004/CatalogService/$metadata

###Read top 2 values
GET http://localhost:4004/CatalogService/EmployeeSet?$top=2

###
GET http://localhost:4004/CatalogService/BusinessPartnerSet

###
GET http://localhost:4004/CatalogService/POs

###
GET http://localhost:4004/CatalogService/POs?$expand=Items,PARTNER_GUID
###
GET http://localhost:4004/CatalogService/POs?$expand=PARTNER_GUID
###
GET http://localhost:4004/CatalogService/POItems?$expand=PARENT_KEY,PRODUCT_GUID

###
POST http://localhost:4004/CatalogService/EmployeeSet
Content-Type: application/json

 {
           
            "nameFirst": "Sagar",
            "nameMiddle": null,
            "nameLast": "Sharma",
            "nameInitials": null,
            "sex": "M",
            "language": "H",
            "phoneNumber": "+91 897566909",
            "email": "Moni.sharma@itelo.info",
            "loginName": "MONI",
            "accountNumber": "111222330",
            "bankName": "SBI bank"
        }

###getting single employee data which was just created by post call
GET http://localhost:4004/CatalogService/EmployeeSet/c41bf294-aab4-40e6-a4b4-70956817225f

###
PUT http://localhost:4004/CatalogService/EmployeeSet/c41bf294-aab4-40e6-a4b4-70956817225f
Content-Type: application/json

{
    "salaryAmount": "56748.90",
    "Currency_code": "INR"
}
###
GET  http://localhost:4004/CatalogService/EmployeeSet/0f47be87-5be1-40d6-b1f0-29fba59a56d3
###
PATCH http://localhost:4004/CatalogService/EmployeeSet/0f47be87-5be1-40d6-b1f0-29fba59a56d3
Content-Type: application/json

{
    "salaryAmount": "100000.90",
    "Currency_code": "INR"
}

### post request using the CDS queries 
POST http://localhost:4004/mysrvdemo/InsertEmployeeSrv
Content-Type: application/json

 {
            "ID" : "02BD2137-0890-1EEA-A6C2-BB55C197A7DE",
            "nameFirst": "Janak",
            "nameMiddle": null,
            "nameLast": "Pareek",
            "nameInitials": null,
            "sex": "M",
            "language": "H",
            "phoneNumber": "+91 897566909",
            "email": "Moni.sharma@itelo.info",
            "loginName": "MONI",
            "accountNumber": "111222330",
            "bankName": "SBI bank"
}

###
PUT http://localhost:4004/mysrvdemo/UpdateEmployeeSrv/02BD2137-0890-1EEA-A6C2-BB55C19787FB
Content-Type: application/json

{
    "nameFirst": "Ananaya",
    "nameLast": "Vishwanathan"
}

###
GET http://localhost:4004/mysrvdemo/ReadEmployeeSrv/ca1c05ae-c8e1-48a8-b3ee-59ab869d281c

###
DELETE http://localhost:4004/mysrvdemo/DeleteEmployeeSrv/ca1c05ae-c8e1-48a8-b3ee-59ab869d281c
###getting a random po
GET http://localhost:4004/CatalogService/POs?$top=5

###
POST http://localhost:4004/CatalogService/POs('02BD2137-0890-1EEA-A6C2-BB55C1978999')/CatalogService.boost
Content-Type: application/json
{}
###
GET  http://localhost:4004/CatalogService/POs('02BD2137-0890-1EEA-A6C2-BB55C1978999')/CatalogService.largestOrder()

###
GET  http://localhost:4004/CatalogService/POs('02BD2137-0890-1EEA-A6C2-BB55C1978999')

##v2 magic
### Get call using v2 for POs
GET http://localhost:4004/v2/CatalogService/POs?$top=5

### custom action using v2
POST  http://localhost:4004/v2/CatalogService/POs_boost?NODE_KEY=02BD2137-0890-1EEA-A6C2-BB55C1978999
Content-Type: application/json

### custom function 
GET http://localhost:4004/v2/CatalogService/POs_largestOrder?NODE_KEY=02BD2137-0890-1EEA-A6C2-BB55C1978999